//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s4pi.TextResource.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("s4pi.TextResource.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x0069453E TS4 XML -- objective
        ///0x029E333B Audio controllers
        ///0x02C9EFF2 Audio Submix
        ///;0x02D5DF13 JAZZ tuning
        ///0x03B33DDF TS4 XML tuning
        ///0x03E9D964 TS4 XML -- pie_menu_category
        ///0x04D2B465 TS4 XML -- achievement_collection
        ///0x074DFB83 TS4 XML -- relbit
        ///0x0904DF10 TS4 XML -- relbit socialcontextbit
        ///0x0C772E27 TS4 XML -- action
        ///0x0CA4C78B TS4 XML -- sim_template
        ///0x0E4D15FB TS4 XML -- role_state
        ///0x0EEB823A Renderer_FadeTuning
        ///0x11E72A63 TS4 XML -- notebook_entry
        ///0x122FC66A Lot type event map 
        ///0x1249 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextResources {
            get {
                return ResourceManager.GetString("TextResources", resourceCulture);
            }
        }
    }
}
